# Langfuse v3 Self-Hosted for Dokploy
# Create as "Compose" service in Dokploy
# Domain: langfuse.49-12-207-132.sslip.io -> langfuse-web:3000

services:
  langfuse-worker:
    image: docker.io/langfuse/langfuse-worker:3
    restart: always
    depends_on: &langfuse-depends-on
      langfuse-postgres:
        condition: service_healthy
      langfuse-minio:
        condition: service_healthy
      langfuse-redis:
        condition: service_healthy
      langfuse-clickhouse:
        condition: service_healthy
    environment: &langfuse-worker-env
      NEXTAUTH_URL: https://langfuse.49-12-207-132.sslip.io
      DATABASE_URL: postgresql://langfuse:JNofiE99DPLVZ3HRXpVg@langfuse-postgres:5432/langfuse
      SALT: 428d4f624ce7fe6c84e80747093050aa
      ENCRYPTION_KEY: 02834c1cb3225134ca4816dfb9a59812da20682c5fa5dd5bf90679c2b8fdfe80
      TELEMETRY_ENABLED: "false"
      LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES: "true"
      CLICKHOUSE_MIGRATION_URL: clickhouse://langfuse-clickhouse:9000
      CLICKHOUSE_URL: http://langfuse-clickhouse:8123
      CLICKHOUSE_USER: clickhouse
      CLICKHOUSE_PASSWORD: VdTebxiRZtK93vTGCOiHIA
      CLICKHOUSE_CLUSTER_ENABLED: "false"
      LANGFUSE_USE_AZURE_BLOB: "false"
      LANGFUSE_S3_EVENT_UPLOAD_BUCKET: langfuse
      LANGFUSE_S3_EVENT_UPLOAD_REGION: auto
      LANGFUSE_S3_EVENT_UPLOAD_ACCESS_KEY_ID: minio
      LANGFUSE_S3_EVENT_UPLOAD_SECRET_ACCESS_KEY: DNZ9zbdtSot6LBgQIfkEg
      LANGFUSE_S3_EVENT_UPLOAD_ENDPOINT: http://langfuse-minio:9000
      LANGFUSE_S3_EVENT_UPLOAD_FORCE_PATH_STYLE: "true"
      LANGFUSE_S3_EVENT_UPLOAD_PREFIX: events/
      LANGFUSE_S3_MEDIA_UPLOAD_BUCKET: langfuse
      LANGFUSE_S3_MEDIA_UPLOAD_REGION: auto
      LANGFUSE_S3_MEDIA_UPLOAD_ACCESS_KEY_ID: minio
      LANGFUSE_S3_MEDIA_UPLOAD_SECRET_ACCESS_KEY: DNZ9zbdtSot6LBgQIfkEg
      LANGFUSE_S3_MEDIA_UPLOAD_ENDPOINT: http://langfuse-minio:9000
      LANGFUSE_S3_MEDIA_UPLOAD_FORCE_PATH_STYLE: "true"
      LANGFUSE_S3_MEDIA_UPLOAD_PREFIX: media/
      LANGFUSE_S3_BATCH_EXPORT_ENABLED: "false"
      REDIS_HOST: langfuse-redis
      REDIS_PORT: "6379"
      REDIS_AUTH: g9aXIewUZ8m6kT56ey9j1g
      REDIS_TLS_ENABLED: "false"

  langfuse-web:
    image: docker.io/langfuse/langfuse:3
    restart: always
    depends_on: *langfuse-depends-on
    networks:
      - dokploy-network
      - default
    environment:
      <<: *langfuse-worker-env
      NEXTAUTH_SECRET: 2b4d5b1b7050f27bfdb947f89fcc64daa7f75078e38caed6901af48a97afc8cb
      # Auto-create initial org/project/user (optional - remove after first login)
      LANGFUSE_INIT_ORG_NAME: AI Job Finder
      LANGFUSE_INIT_PROJECT_NAME: Production
      LANGFUSE_INIT_USER_EMAIL: admin@example.com
      LANGFUSE_INIT_USER_NAME: Admin
      LANGFUSE_INIT_USER_PASSWORD: changeme123!

  langfuse-clickhouse:
    image: docker.io/clickhouse/clickhouse-server
    restart: always
    user: "101:101"
    environment:
      CLICKHOUSE_DB: default
      CLICKHOUSE_USER: clickhouse
      CLICKHOUSE_PASSWORD: VdTebxiRZtK93vTGCOiHIA
    volumes:
      - langfuse_clickhouse_data:/var/lib/clickhouse
      - langfuse_clickhouse_logs:/var/log/clickhouse-server
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8123/ping || exit 1
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 1s

  langfuse-minio:
    image: cgr.dev/chainguard/minio
    restart: always
    entrypoint: sh
    command: -c 'mkdir -p /data/langfuse && minio server --address ":9000" --console-address ":9001" /data'
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: DNZ9zbdtSot6LBgQIfkEg
    volumes:
      - langfuse_minio_data:/data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 1s
      timeout: 5s
      retries: 5
      start_period: 1s

  langfuse-redis:
    image: docker.io/redis:7
    restart: always
    command: >
      --requirepass g9aXIewUZ8m6kT56ey9j1g
      --maxmemory-policy noeviction
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "g9aXIewUZ8m6kT56ey9j1g", "ping"]
      interval: 3s
      timeout: 10s
      retries: 10

  langfuse-postgres:
    image: docker.io/postgres:17
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U langfuse"]
      interval: 3s
      timeout: 3s
      retries: 10
    environment:
      POSTGRES_USER: langfuse
      POSTGRES_PASSWORD: JNofiE99DPLVZ3HRXpVg
      POSTGRES_DB: langfuse
      TZ: UTC
      PGTZ: UTC
    volumes:
      - langfuse_postgres_data:/var/lib/postgresql/data

networks:
  dokploy-network:
    external: true

volumes:
  langfuse_postgres_data:
    driver: local
  langfuse_clickhouse_data:
    driver: local
  langfuse_clickhouse_logs:
    driver: local
  langfuse_minio_data:
    driver: local
